// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eImovina.Api.Data;

#nullable disable

namespace eImovina.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913175513_RemoveEmployeeEmailAndJobTitle")]
    partial class RemoveEmployeeEmailAndJobTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("eImovina.Api.Data.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InventoryManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LocationResponsible"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.AssignmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssignmentStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Aktivno"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Vraćeno"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Premješteno"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Stornirano"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("EquipmentStatusId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Equipment_InventoryNumber");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Equipment_SerialNumber");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignmentStatusId");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Assignments_OneActivePerEquipment")
                        .HasFilter("AssignmentStatusId = 1");

                    b.ToTable("EquipmentAssignments", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Računalo"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Mrežna oprema"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Namještaj"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Alat"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Ostalo"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoverImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_EquipmentFiles_OneCoverPerEquipment")
                        .HasFilter("IsCoverImage = 1");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("EquipmentFiles", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DecisionAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecisionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedEquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequesterEmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DecisionByUserId");

                    b.HasIndex("EquipmentCategoryId");

                    b.HasIndex("RelatedEquipmentId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequesterEmployeeId");

                    b.ToTable("EquipmentRequests", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Na skladištu"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Zaduženo"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Na servisu"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Nedostaje"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Otpisano"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OpenedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsibleEmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InventoryStatusId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.ToTable("Inventories", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoundLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDamaged")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsFound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotEquipmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotInventoryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotStatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ExpectedLocationId");

                    b.HasIndex("FoundLocationId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ProcessedByUserId");

                    b.HasIndex("InventoryId", "EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_InventoryItems_OnePerEquipment");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.InventoryStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InventoryStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Nacrt"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Otvorena"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "U tijeku"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Završena"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Zaključana"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Ured"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Škola"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Skladište"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Terenska lokacija"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RequestStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "U obradi"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Odobreno"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Odbijeno"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Realizirano"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Zatvoreno"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.WriteOffRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DecisionAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecisionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExecutedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WriteOffRequestStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DecisionByUserId");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_WriteOff_OneOpenPerEquipment")
                        .HasFilter("WriteOffRequestStatusId NOT IN (4, 5)");

                    b.HasIndex("ExecutedByUserId");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("WriteOffRequestStatusId");

                    b.ToTable("WriteOffRequests", (string)null);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.WriteOffRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WriteOffRequestStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Zaprimljeno"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "U obradi"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Odobreno"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Odbijeno"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Provedeno"
                        });
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.AppUser", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.AppUserRole", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Employee", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Equipment", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.EquipmentCategory", null)
                        .WithMany()
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.EquipmentStatus", null)
                        .WithMany()
                        .HasForeignKey("EquipmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentAssignment", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AssignmentStatus", null)
                        .WithMany()
                        .HasForeignKey("AssignmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentFile", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.EquipmentRequest", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("DecisionByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.EquipmentCategory", null)
                        .WithMany()
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("RelatedEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.RequestStatus", null)
                        .WithMany()
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("RequesterEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Inventory", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.InventoryStatus", null)
                        .WithMany()
                        .HasForeignKey("InventoryStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("ExpectedLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("FoundLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.Location", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.LocationType", null)
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eImovina.Api.Data.Entities.WriteOffRequest", b =>
                {
                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("DecisionByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ExecutedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eImovina.Api.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eImovina.Api.Data.Entities.WriteOffRequestStatus", null)
                        .WithMany()
                        .HasForeignKey("WriteOffRequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
